services:
  postgres:
    image: postgres:16-alpine
    container_name: bank-cards-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bank_cards
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d bank_cards"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
